### ISSUE TITLE
Amino acid property plot

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#103]
The name and the desired outcome for this issue are likely to change (and maybe spawn further issues), but I'm erring on the side of creating the issue early rather than late, to have a history of the discussion.

@lauradoepker expressed today during group meeting the lack of an existing tool/method for visualizing patterns in the properties of amino acids in certain regions (CDRs) of a heavy chain sequence. The idea as I interpreted it was there might be some recognizable pattern of the various properties, sequentially / by position, that would help in characterizing and comparing these regions across certain BCR sequences to observe a characteristic pattern for those that we have observed as binding or neutralizing.

As of v1, Laura says we can start by just reducing the dimensions of the amino acid space to [these categories](https://www.sigmaaldrich.com/life-science/metabolomics/learning-center/amino-acid-reference-chart.html) and just show these categories at each position (maybe by color) in the CDR3s of antibodies we know bind an epitope to look for a pattern there.

@lauradoepker since you said that we should just look at some curated list of BCR sequences (CDR3s specifically) based on patterns of binding you have observed in your work, maybe we don't need this on Olmsted for v1 (especially if the data you care about seeing is hasn't run its course through the partis, cft, etc pipeline), so much as we just need a place to view a vega visualization of those data for the curated list. Does that make sense / sounds right? If so this is totally possible.

**Comment by lauradoepker** [comment]
That's right, @eharkins:  you should just create this visualization as a separate entity apart from Olmsted.  I haven't made the larger list yet, but to begin with please visualize (I have NOT included the anchor residues at beginning and ends):

VRC01 CDRH3: TRGKNCDYNWDFEH
PGT 128 CDRH3: FGGEVLRYTDWPKPAWVDL
PGT 121 CDRH3: TLHGRRIYGIVAFNEWFTYFYMDV
BF520.1 CDRH3:  ARGPFPNYYGPGSY

VRC01 CDRL3: QQYEF
PGT 128 CDRL3: GSLVGNWDVI
PGT121 CDRL3: HIWDSRVPTKWV
BF520.1 CDRL3:  QQYNNWPSPFT

**Comment by eharkins** [comment]
Got it; I'll get started on that. To start I'm just color coding by category. @lauradoepker should I align them all starting at the first position given in the above sequences? And should the light / heavy be positioned relative to each other in any particular way or just separate rows?

**Comment by lauradoepker** [comment]
@eharkins   Yes, color coding is a good start.  Perhaps also include larger size for aromatic (bulky) AAs.  You can align either by first position or "center" all of them, since they vary in length and thus they vary in how much they bulge out of the main antibody structure.  Heavy and light are entirely separate entities, so separating them by rows is reasonable.  Thank you!

**Comment by eharkins** [comment]
This is what I have so far:
Heavy:
![screen shot 2018-11-21 at 6 48 07 pm](https://user-images.githubusercontent.com/12140437/48879092-2def6400-edbf-11e8-829d-93a51431158e.png)
Light:
![screen shot 2018-11-21 at 6 49 37 pm](https://user-images.githubusercontent.com/12140437/48879093-2def6400-edbf-11e8-925f-08ceb688ae98.png)
After showing Laura, she says: 
* I see why aligning them by starting position is helpful instead of centering.  Leave this as it is - we can change it later if it suits us.
* It will be really important to make acidic red and basic blue. These are really prominent biochemical features.
* Unique could be grey (though I like yellow too) as these ones are understated AAs

**Comment by eharkins** [comment]
Note(s) to self:
* Keeping vega [here](https://gist.github.com/eharkins/e9117b8eb5708e8321ea40ca51d84754)
* Right now to change heavy to light, just change CDRH3 to CDRL3 in a few places; try separating them in data in order to do facet by: heavy vs light field

**Comment by metasoarous** [comment]
What's the status on this?

* Does this just need to be a little utility function for running on random input here and there?
* Would this be helpful as a color setting (dropdown selection) on the main tree/alignment visualization in Olmsted? An alternate coloring scheme shouldn't be too hard to come up with.
* Something else?

**Comment by lauradoepker** [comment]
@metasoarous Eli completed this for me but it's not important to integrate into Olmsted.  It was an exploration.
