### ISSUE TITLE
Visualize LBR/LBI and affinity in tree

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#106]
@psathyrella has expressed interest in seeing Local Branching Rate (LBR) and/or Local Branching Index (LBI) against affinity in ancestral sequence reconstruction visualizations. This could go many ways, so we need to experiment with some designs. But first we need these data per sequence in the tree, which are available through some additions to CFT by Duncan, but we have not had a chance to build new data with these changes yet. @metasoarous  / @psathyrella correct me if any of this is inaccurate please!

**Comment by matsen** [comment]
https://nextflu.org/help/ 

![image](https://user-images.githubusercontent.com/112708/49473678-911dc500-f7c7-11e8-9768-9b58baae7ba1.png)


LBR = local branching ratio

**Comment by eharkins** [comment]
Thanks @matsen! @psathyrella talked about coloring by LBI with affinity mapped to thickness of branches or opacity (my vote is for opacity).

**Comment by psathyrella** [comment]
Great, looking forward to it. I guess I should actually get around to thinking about the possible ways to represent two per-node numbers on the tree. So starting with what you mention above

  - one uses color, the other uses line thickness
  - (  "  ), the other uses opacity

Are we thinking these would be nodes or branches for one or both numbers? What if branches are colored/opacitied for lbi, and nodes are colored/opacitied for affinity? For really dense trees, I could see opacity and size being hard to see, and this would let us use color for both the lb metric and affinity. 

Also in the vein of line thickness, we can maybe vary both line thickness and node size, as well as the presence/absence of nodes/dots? I can't figure out what the presence/absence of dots in the nextrain help is, but it's another degree of freedom.

**Comment by metasoarous** [comment]
@eharkins Lol; First of all, I'm not csmall here. Craig in Australia is probably wondering WTF. Anyway...

Bottom line is that as with the rest of the visualizations, I think we should make everything configurable via dropdowns, but figure out sensible defaults. My initial gut was that LBI would map to thickness, as that's the easiest aesthetic to see. But I suppose there's value in following the lead of Nextstrain with respect to whatever their defaults are.

In general I prefer branch aesthetics to internal node aesthetics, though I'll admit some of this is trauma from having wrestled with ete3 which does weird things with the spacing between branches. Still, I'd vote for squeezing as much out of branch aesthetics that we can before going down that the path of adding internal nodes. For one thing internal nodes will add some visual dissonance when taken in conjunction with tip nodes.

**Comment by eharkins** [comment]
We need to take a look at https://vega.github.io/vega/docs/transforms/treelinks/ and https://vega.github.io/vega/docs/transforms/linkpath/ to see how we can associate qualities of the child that the branch goes to with qualities of the branch itself. That is, do things like assign LBR based width to a branch based on the LBR of its child.
