### ISSUE TITLE
Top level gene locus selection

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#109]
per Laura's feedback, it doesn't make any sense to have clonal families with different antibody gene loci in the same plots. The user should be able to select which locus the sequences (in the families they are viewing) are from, and this will filter the input data for the initial scatterplot. @lauradoepker or @metasoarous correct me on the details of this if necessary please!

We should be able to do this with vega. Otherwise it can happen at the react level if needed.

**Comment by metasoarous** [comment]
One quick note: We'll want an "all" option so that users can do a facet by "locus" if they're so inspired.
