### ISSUE TITLE
Generlize input data model

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#115]
We may want to look at something like json-schema in order to make clearer the shape of data required by olmsted, en route to making it a more general purpose tool:

http://json-schema.org/learn/getting-started-step-by-step.html

**Comment by metasoarous** [comment]
Thinking about this a little more, I think what we want to do is have an ingest script, something like `bin/process_data.py` which takes in data in a specified format, and processes into compatible output. Bulk of the work here will be in deciding where to draw lines as far as what is required and what isn't, and then making the necessary generalizations in Olmsted to handle the optional cases.

**Comment by metasoarous** [comment]
See new branch 115-generalize-input for some wip in this.

**Comment by metasoarous** [comment]
Note also that we'll want to take this opportunity to do a pass through all the data as currently stored in Olmsted and clean things up to match the input schema as much as possible as we're doing this. There's some thinking and discussion on the commit comments here: https://github.com/matsengrp/olmsted/commit/4992ac4af5be0ef1d12034de37666c6cf7258988#commitcomment-32294426.

Focus should be on consistency and clarity semantically, and could benefit from a pass through with @psathyrella & @lauradoepker if possible. Once we're happy with the schema, I'd like to take a grow-only (no-breaking changes) approach, so this is the time to get things right.

**Comment by eharkins** [comment]
@matsen @metasoarous Re auspice and how they handle this kind of thing:
https://nextstrain.org/docs/bioinformatics/output-jsons/
Basically they use json [schema](https://github.com/nextstrain/augur/blob/master/augur/data/schema.json), where the tree is a nested json object. Maybe this is old news but Erick was asking about how they handle the tree specifically, if I remember correctly. Anyway, more info @ https://nextstrain.org/docs/visualisation/introduction/#auspice-is-agnostic-about-where-the-data-came-from

**Comment by metasoarous** [comment]
After thinking about and looking into this a bit, I think it's best to start by supporting newick. The nexus-json thing does not seem super widely adopted, and asking folks to take their newick and turn it into such a format does not make sense to me, when we're just going to do our own post processing on it anyway. I'm certainly game for adding an _option_ of specifying the data in either auspice or newick json format, and in fact, depending on how the tree transform work pans out, I could see passing data in to Olmsted in a similar format. But it would still seem like a nice feature to continue supporting the newick string.

**Comment by eharkins** [comment]
On board with the newick comments. The vega tree transform basically doesn't change anything except how the height of nodes in the tree is calculated (it does this in the transform instead of us having to do this in the processing script.

**Comment by psathyrella** [comment]
I would agree with sticking to newick. I did a bunch of poking around the other formats recently after realizing that everyone seems to feel the need to smoosh extra information into their newick files that doesn't fit in the standard, and which then breaks other people's newick implementations. But the non-newick formats didn't in the end seem wildly better, especially considering their comparative lack of support.

**Comment by metasoarous** [comment]
@eharkins @psathyrella Word; Thank you both for the feedback.

**Comment by metasoarous** [comment]
This work is now more or less complete. Our `bin/process_data.py` script is working, and I've tested its output on some data I mocked up from CFT output. The one thing left to do is standardize naming conventions and such (as well as documentation), but as this is going to be an involved process in its own right, I'm going to fork this off into its own issue, and close this.
