### ISSUE TITLE
Static/serverless public deployment

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#117]
Originally, I thought we'd be using one of:

* https://surge.sh - Deploy a static site to a surge.sh address with a single shell command: `surge <deploy-directory> <url>`
* [Github Pages](https://github.io) - Push static build to a GitHub project, and set up as a GitHub page

The main challenge here is what we do with the data. The easiest thing to do is just serve all the data directly as part of the static deployment (index.html and compiled bundle.js). I could tell pretty quickly that surge.sh would not be able to serve our large dataset files, and after looking into whether GitHub pages would be able to accommodate large files using the LFS system, it looks like it might be possible, but I suspect that we'd pretty quickly surpass the throughput constraints of the service. I've contacted them to see if there's a way to get around this, but I have a feeling we're not going to be able to serve the data via either of these methods.

The simplest solution is likely therefor to serve the data using S3. And if we're doing that we may as well also serve the main assets (`index.html`, `bundle.js`, images, css, etc.) alongside in the same bucket, since otherwise we'd have to somehow code in the app deployment where data is fetched from, which only introduces complexity.

Regardless of which of these deployment routes we take though, most of the work involved is going to be in rewriting all of the request routing to exactly match the static file structure. On the bright side, we should be able to get rid of much of the file server (charon) code from Auspice, which was probably never really necessary in the first place. If we end up on S3, we'll also have to write a couple of scripts for deploying the content, which should have separate subcommands or flags for deploying data vs everything else.

**Comment by eharkins** [comment]
This makes sense to me. So if we are using S3 to serve all files including data and main assets, do we still need to set up a host (through S3 or otherwise) to make the app publicly available?

**Comment by metasoarous** [comment]
No; it'll have some weird aws domain by default, but we can easily add a custom domain.

**Comment by eharkins** [comment]
But we have to do [something?](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html) to deploy to that aws domain, right?

**Comment by metasoarous** [comment]
Oh; yes, of course. We just have to push up to the bucket and make sure it has the correct permissions I believe, and then check a box on properties page to make it a website. I thought you meant adding additional CDN or custom domain, which we can still accomplish.

**Comment by eharkins** [comment]
We are already tracking incomplete data builds in #94 but I thought it was worth mentioning that some of the data available on the deployment @ http://olmsted-deploy.s3-website-us-west-2.amazonaws.com/ were not fully built. We just need a few datasets available there (preferably smaller ones since loading them from s3 is of course slower than using our local network). I can delete the others from the s3 resource storage if you help me figure out how @metasoarous

**Comment by metasoarous** [comment]
I think it's better to leave a variety up, but yes, I'll take down the ones with broken clusters.

**Comment by metasoarous** [comment]
We've got a more or less stable deployment of the datasets up at `olmstedviz.org`, so I'm gonna call this issue closed for now.
