### ISSUE TITLE
Dataset loading indicators don't initialize properly on app url

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#120]
When you visit an app url with datasets specified in the query string, it should show which datasets are loading but doesn't until they're actually done loading.

**Comment by eharkins** [comment]
Race condition of loading the datasets info (which datasets are available to load) after already dispatching the action to update the loading status of a particular dataset:
![Screen Shot 2018-12-31 at 3.06.44 PM.png](https://images.zenhubusercontent.com/5b523735b69de9433c05431a/734e38fd-37b9-4577-96df-9c01a87159b9)

**Comment by metasoarous** [comment]
Thanks for clarifying here. That makes perfect sense.

I agree that stripping things away would be good. I really regret now starting from that template, because we've ended up with such a different application.
