### ISSUE TITLE
Sliders only work in Chrome

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#125]
@metasoarous and I have both experienced that in Firefox if you move one of the sliders rendered by Vega for the tree component, they will instantly reset themselves. This seems new but we agree that it seems like either a CSS oddity or a Vega bug because there are no Redux actions being triggered by these sliders that might cause an actual reset of the viz (and because this only happens in Firefox).

**Comment by metasoarous** [comment]
I think this is important: If we're sending this link out to the world, we need to either be explicit that we only fully support Chromium, or fix the root issue (preferable, if we can).

Again, from the evidence above it looks like this may be a Vega-related issue. First step should be to update the vega libs, as that can sometimes be all it takes to fix little issues like this. If that doesn't work though, we should raise a vega issue.

**Comment by eharkins** [comment]
This is an issue in Safari too, in a slightly different way where once you have clicked on the slider, it won't stop changing the value when you release the mouse. 

Hopefully I can fix this before we publish a paper, otherwise we need to say in the paper that only chrome is supported.

**Comment by eharkins** [comment]
[This example](https://vega.github.io/vega/examples/pi-monte-carlo/) with a slider works in FF and Safari.

**Comment by eharkins** [comment]
[relevant](https://stackoverflow.com/questions/54755769/input-range-slider-stuck-in-firefox)

**Comment by eharkins** [comment]
[`events.cosume = true`](https://vega.github.io/vega/docs/event-streams/ ) (aka [`event.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)) was the cause of slider issues in both Firefox and Safari, in particular on [this `mouseUp` Signal](https://github.com/matsengrp/olmsted/blob/master/src/components/explorer/vega/facet_scatter_plot.js#L196), which is not even the vega spec in question here with the broken sliders, but since it was scoped to the while `window` it affected the mouseUp events everywhere on the page.

That should close this, but now I'll double check that:
- we didn't have that field set for a good reason
- it being set in other places doesn't have other unintended consequences.
