### ISSUE TITLE
Front-end testing

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#126]
It would be pretty cool if we had front-end tests that made sure we didn't undo our own efforts with new commits. This is not a trivial thing to implement of course, but we could have some minimal set of things that must work, since we do have a relatively limited number of things to break on our app.

I will start looking at into the simplest ways to get started on this.

@metasoarous did you recommend looking at https://github.com/SeleniumHQ/selenium/tree/master/rb or was it something else?

**Comment by matsen** [comment]
Er, in principle I agree but in practice we need to move this along. Users will report breakages. When they complain you can refer them to this issue and how I am a terrible person.
