### ISSUE TITLE
Autoselect first family upon page load?

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#128]
@metasoarous and I discussed that in [defaulting to the clonal family at index 0](https://github.com/matsengrp/olmsted/blob/master/src/selectors/clonalFamilies.js#L109), we are not defaulting to the first one in the table necessarily, because it is sorted. This can easily be fixed by using an existing selector to draw from the first page in the table. However, we still need to decide why we are doing this and the intended behavior:

Do want to (upon loading the page) autoselect the first family in the table in all respects / render things as such in all components? 

Or was the defaulting more of just a way to always have the selector return something?

The former would involve making a request for the appropriate reconstruction, otherwise it will just show "loading data for X" because the family was selected but no request was made. Do we in fact want to auto-request the first reconstruction in the clonalfamiliespage[0] family when we load the page?

Not a huge deal either way, we should just decide on one if you agree that being in the halfway state described above is not ideal.

**Comment by metasoarous** [comment]
Thanks for pointing this out @eharkins.

I think we do want to autoselect the first family in the table. Clicking around on table headers and adjusting the sorting, it's nice to quickly get a view of an extrema for the selecting sorting metric.
