### ISSUE TITLE
Make deployment infrastructure accessible

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#131]
Right now @metasoarous is the only one with the keys to the car, that is, the aws deployment at olmstedviz.org. We should do some account transferring etc so that AWS doesn't charge either of our accounts if we go over whatever free limits exist, and so that I can update the code running there.

**Comment by metasoarous** [comment]
This is done now, as everything has been moved over to Erick's AWS & Namecheap accounts, and @eharkins has successfully deployed the application.
