### ISSUE TITLE
Transition to vega tree transform

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#132]
Right now we are writing in explicit height values for tree nodes, so that the nodes can be displayed along the tree diagram's y-axis in the correct spot. Leaves go from 0-max_height, and a parent is the avg height of its children. This isn't very flexible, and we'd like to move to using the [vega tree transform](https://vega.github.io/vega/docs/transforms/tree/) instead. One benefit of this that @metasoarous has expressed interest in is being able to sort leaves / branches / clades by some metric. So if two children fork from a node, the child with higher LBR goes left (or up), for example, to help you focus on certain metrics.

There was some discussion of whether our expectations for tree data being input to the front end code (aka vega) would be inaccessible for those who just have a newick string. Regardless, I think we still may have to transform said newick string in our simple non-cft processing script into something vega can handle, aka some node objects (with or without metadata depending on ones data).

**Comment by metasoarous** [comment]
Thanks for putting this up.

Agreed: the "import/ingest" script (where all the json-schema stuff does) should be doing all of the processing of things like newick to whatever json representation we are going to be using. But simplifying that transformation by letting vega handle it's own tree layouts is a major plus.

**Comment by eharkins** [comment]
For the record we will just be using y (height) values for tree nodes from the vega transform, and using the existing `distance` field still to determine x (length of branch).

**Comment by eharkins** [comment]
https://github.com/matsengrp/olmsted/compare/ba4957609bc4...5c4e518573c6
