### ISSUE TITLE
produce schema documentation

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#139]
Would be nice to have an easy way to generate schema documentation from the schema data itself. The simplest thing here is to just pretty print out the schema json, as it's actually fairly easy to read just like that. But we could also produce some simple HTML or markdown output, which is then visible on the website or GitHub, as appropriate.

**Comment by matsen** [comment]
JSON Hyper-schema? http://json-schema.org/

**Comment by eharkins** [comment]
http://www.olmstedviz.org/schema.html
