### ISSUE TITLE
Line up tree nodes with sequence alignment 

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#14]
We need a way for the tree nodes to be evenly spaced: https://github.com/vega/vega/issues/1399
Then we need to match up their height with the y axis of the alignment viz, whether explicitly or just by lining up the size and spacing

**Comment by metasoarous** [comment]
This looks good, but now we're seeing the node labels drift away from the nodes:
![image](https://user-images.githubusercontent.com/88556/44565563-9c1f7e80-a71d-11e8-978a-c4a597a677a3.png)

**Comment by eharkins** [comment]
Closing because this mostly works and I have opened https://github.com/matsengrp/olmsted/issues/23. Might open vega issue depending on feedback from them on slack
