### ISSUE TITLE
frozen deployments

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#141]
See https://github.com/matsengrp/cft/issues/283

For reproducibility's sake, when we create local deployments on our servers used by @lauradoepker and @mmshipley, we would like to be able to "freeze" a version of Olmsted used for a given deployment (along with the cft data processed and published there, which inherently also includes the cft commit string). Branches seems like a good way to record this.

e.g. check out a branch when running a local server for Laura and Mackenzie, and create a directory associated with that branch from which to serve its data. Then everything about that version of Olmsted, along with the cft data used (save a script showing how we ran bin/process_cft_data.py) is frozen and we can continue to develop Olmsted.

**Comment by eharkins** [comment]
Assuming we want to serve data from various frozen versions of Olmsted at once, this would require having a bunch of different olmsted checkouts (one for each frozen deployment), but the source code of Olmsted does not take up a lot of space. We could house these all adjacently in the file system. 

Once we created the Olmsted checkout and moved the appropriate processed data into that directory, starting that server would be as simple as:
```
cd frozen_olmsted_checkout_of_interest
ml nodejs
npm install
npm start localData data/data_dir_of_interest any_available_port_number_on_host
navigate to host:port
```
@lauradoepker @matsen let me know if this sounds off-base or overly complicated

**Comment by lauradoepker** [comment]
sounds fine to me! @eharkins

**Comment by metasoarous** [comment]
This all sounds great @eharkins. However, we might want to use tags instead of branches, as that's a more standard pattern for managing releases, and doesn't clutter the project with a billion branches.

**Comment by metasoarous** [comment]
One more thing; If it's just new data, you can always add to to the most recent deployment and restart, and that's probably the right way to do things when there aren't also code changes which need to go up.

**Comment by eharkins** [comment]
Thanks @metasoarous both good points!

**Comment by eharkins** [comment]
See https://github.com/matsengrp/olmsted/releases

and `/home/matsengrp/working/eharkins/frozen_checkouts/olmsted`
