### ISSUE TITLE
Add static schema page on olmstedviz.org

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#142]
We should take the html schema docs output of our `process_data.py` script and deploy that together with the application at `olmstedviz.org/schema.html`. Would be nice to have easy an easy to reference url with the most up to date schema definitions & documentation.

@eharkins This would actually be super helpful for #138 to have the current schema up somewhere that Laura, Duncan & Erick can look at easily. I'd like to get their feedback on a few points, and it may be easier for them to answer the questions if they have a better sense of the schema as a whole. It will also be useful for pointing collaborators to once we've #138 is resolved. Would you please make some time to knock this out? Should just be a matter of putting the file in with the rest of the static compliation and then running the deploy script.

Thanks!

**Comment by matsen** [comment]
Yaaaas 👍

**Comment by eharkins** [comment]
http://www.olmstedviz.org/schema.html
