### ISSUE TITLE
Lineage sequences should be unique

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#19]
If in a lineage we see the same sequence multiple times in a row, we don't really need to see it more than once in the lineage viz. So in processing the data through for that viz, we should just keep the first such sequence when we have these successive duplicates.

However, care should be taken to allow for back-mutations to show up in the viz. If A -> B -> A -> C, we should in fact show sequence A twice in the lineage succession.

This is from #cftweb/13.

**Comment by eharkins** [comment]
Laura says that this is not as much of a concern as it once was, given that we have the tips alignment and the lineage. Should we close this @lauranoges?

**Comment by metasoarous** [comment]
@lauranoges It sounded like you weren't so sure about this anymore. Let us know if you think we should plan to eventually do it, or just scrap it.

**Comment by lauranoges** [comment]
The only reason to still do it is to present a cleaner lineage that will take less space. I think that’s probably worth it eventually, yes. The only info we’re losing is the quantity of times that the node is observed - does this mean anything in real life? Like we should trust that intermediate/node more? Meh.

**Comment by metasoarous** [comment]
I think its interesting to think about where mutations are happening in tree, and the duplications kind of help get that across, but not super cleanly. Maybe when you hover on a lineage sequence, it highlights the corresponding internal nodes of the tree which had that sequence? We could perhaps somehow annotate the tree with where the mutations pop, but that could get messy quickly.

**Comment by metasoarous** [comment]
I think its interesting to think about where mutations are happening in tree, and the duplications kind of help get that across, but not super cleanly. Maybe when you hover on a lineage sequence, it highlights the corresponding internal nodes of the tree which had that sequence? We could perhaps somehow annotate the tree with where the mutations pop, but that could get messy quickly.

**Comment by lauranoges** [comment]
Sure, that sounds good.  We’re still losing the info about how many times an internal node would be repeated… but again, I don’t think that that info is telling us anything “real” anyway.

**Comment by lauranoges** [comment]
The nodes on the tree would be potentially overlapping (x axis) though they may be separated by y axis.  Yeah, sounds good.

**Comment by eharkins** [comment]
Just closed #20 as you can see above, we now have these download buttons. Consequently, the work is done (see discussion in #20 referencing the desired behavior from this issue) to allow for this issue to be closed with a simple change. Just depends on what we want to do: we can have the behavior described in the original description of this issue, by aa or nt seq if we want.

**Comment by metasoarous** [comment]
@lauradoepker Do you have an opinion here regarding deduplication?

**Comment by lauradoepker** [comment]
For lineage we want no duplicates unless they are spaced apart by a sequence (i.e. a back mutation), which is what is described in original post on this issue.  Download nt.  View aa.

**Comment by eharkins** [comment]
After chatting with @lauradoepker today, we want to (in all cases - both for the fasta download and the lineage visualization) de-duplicate at the nucleotide level. This I think is actually happening already, so we just need to change the set of sequences to be displayed in the lineage viz to match this set of sequences de-duplicated at the NT level, but of course we still want so see AA sequences.
