### ISSUE TITLE
brush select should automatically select the first tree in the table

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#2]
This way, as you brush around, you can get some sense for what the trees in the space look like.

**Comment by metasoarous** [comment]
I think in talking about this in slack we decided that with all the questions issues mentioned above, it seems like we should at least lower priority. Is this still something we want to eventually consider?

The goal in my mind is that it would be nice if brushing around you could get a sense for what the trees in a particular part of the space look like as evidenced through some exemplar that updates as you move around. So if its possible and we're looking for cool things to do down the road, and want to tackle the design and implementation challenges, it's worth a consider.

**Comment by eharkins** [comment]
Laura says at the very least we want to clear the selected family upon brush selection. One idea if we want to do this is to select the first table upon releasing the brush selection. Later could be able to pin one or multiple of the selected family views

**Comment by eharkins** [comment]
Where did we land on this for v1? Should we clear it or is it useful to keep the selected family around while using the table to look at others?

**Comment by metasoarous** [comment]
@lauranoges Where are you at on this for v1?

**Comment by lauranoges** [comment]
We should have each new brush select clear the tree results. Do not select the first tree. On that note, pinning would be helpful, but not crucial for v1.

**Comment by metasoarous** [comment]
OK; Closing this issue then, and opening another for clearing the results.

**Comment by eharkins** [comment]
@metasoarous I wanted to check where we had landed on this based on our conversation today. It seems like Laura's view is that we should not auto-select the first tree.

**Comment by metasoarous** [comment]
Let's bring it up again when we meet. I think part of her conclusion may have been because I raised concerns about how we would do it.

**Comment by metasoarous** [comment]
I'm going to open again for now so we can rethink it. Maybe this should be a mode or something but not the default? The basic idea here is to be able to minimize the number of clicks it takes to see some new trees. Right now it's two clicks, including a scroll down to manually pick a clonal family from the table. May seem small, but if you want to quickly look at lots of trees, it's a flow-kill.

**Comment by lauradoepker** [comment]
Yes, totally.  Do that.  Just don't allow any tree to be displayed that isn't currently in the brush select area (i.e. when a new brush select is done, change to new trees... first in list or whatever).  @metasoarous

**Comment by eharkins** [comment]
Closing this since #84 and #86 are closed and the above commit added this feature.
