### ISSUE TITLE
Buttons to download full alignment or focus lineage alignment

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#20]
As with cftweb, need the ability to download the entire set of sequence in one or the other of these views. Complements #17.

**Comment by eharkins** [comment]
Just to clarify, we want a button that downloads a Fasta file of all the nucleotide sequences for a given family, and a separate button that does the same for the lineage mode for just those in the lineage. Is that right?

**Comment by lauradoepker** [comment]
That’s right.  Can the lineage button exclude duplicate node sequences so that we don’t have 15 of the same sequence in some cases?

**Comment by metasoarous** [comment]
Yes, and yes.

**Comment by eharkins** [comment]
* Lineage mode:
So then do we want to have the effect of #19 where we keep sequence 'A' twice if the lineage looks like A->B->A? Or for the purpose of the Fasta download we truly just want the list of unique sequences from the lineage. 

* Entire family / non-lineage mode:
For the download button for the entire family, do we not care about duplicate sequences of internal nodes? Do we want internal nodes or just leaves for this entire family download?

**Comment by lauradoepker** [comment]
Lineage mode: definitely include it twice (in order).
Family: Yes, lets have it include nodes, but not duplicate nodes.
