### ISSUE TITLE
Highlight table-selected clonal family in viz

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#3]
Clonal family selected in table should be highlighted/denoted on the main clonal families viz (size/opacity/whatever).

**Comment by eharkins** [comment]
It turns out making the selected family show up even without #46 is non trivial because you still subscribe to changes to the selected family in the scatter plot to make a solution to this issue possible. However, when you select a family, it gets rid of your brush selection when it re-renders to show the selected family. We are looking into some way to change the data going into the viz without re-rendering it through Vega's API. See https://vega.github.io/vega/docs/api/view/#view_change

**Comment by eharkins** [comment]
@metasoarous, were you thinking of basically forgoing react-vega if we needed to for the sake of being able to use the view API and just build our own components with that? Haven't found much reference to being able to use methods of the view API as opposed to view properties. They say "Props correspond to Vega's View Component API", but it's unclear how this maps to the new View API using things like the above `view.change()`. This seems like someone has already created an issue for this in react-vega: https://github.com/kristw/react-vega/issues/23 so maybe we should voice our interest in a solution to that issue and then move on to working on our own solution that allows the use of the view API for updating view data in a react component.

**Comment by metasoarous** [comment]
Take a look at the implementation of React-Vega: https://github.com/kristw/react-vega/blob/master/src/Vega.jsx.

If you look at the `componentDidUpdate` function there, it's going through and somewhat intelligently looking at changes in props and deciding what of the underlying vega functions to call. Some interesting things caught my eye, like the way that they check whether certain data is equal or not (by casting as a json string?; must be some js hack...). Overall their scheme looks very similar to what I was thinking though, where when you instantiate a `Vega` component, it calls the Vega View API to insert the Vega machinery onto some dom node that you've created for it, and then you have the component maintain a handle on the `view` so that you it can call the view methods on it when the props change.

The key here may be in simply making sure that the spec and data are passed in separately, not with the data as part of the spec. It could be recompiling as though the spec changes any time input data changes. If it still clears the brush selection the way that the data is presented now, maybe one of the [named data sources](https://vega.github.io/vega-lite/docs/data.html#named) or [datasets](https://vega.github.io/vega-lite/docs/data.html#datasets) features would give us a way of making it so that the data being selected isn't being updated, which may be enough to preserve the selection? Maybe a separate named data source or dataset could be just the data of the one selected point. You could paint a semi opaque halo around the point in its own layer. But the brush selection would be on a different layer with the other dataset, and if that dataset not changing is enough to know that the brush selection won't clear, maybe that would be the ticket.

**Comment by eharkins** [comment]
The `json.stringify` is like using `_.isEqual` for deep equality check of objects in JS. I'm slightly confused about the fact that they are using `spec.data && props.data` and looking up data in these arrays by the `name` field at https://github.com/kristw/react-vega/blob/master/src/Vega.jsx#L91-L92 but I see your point and the general idea that we should give it some data in props that will end up being compared and it will run `vega.changeset()` @ https://github.com/kristw/react-vega/blob/master/src/Vega.jsx#L185 and update the data that needs updating without running `createView()`
