### ISSUE TITLE
Show multiple cluster sizes on tree and minadcl seq vizs

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#44]
Probably different size drop down selections, one for each of the different size aggregation steps.

**Comment by eharkins** [comment]
@metasoarous would you mind reminding me of the details of what we are trying to show here and what the end result will be for the UI / the tree viz?  I'm confusing this with another issue I think.

**Comment by metasoarous** [comment]
There are several different aggregation levels for timepoint multiplicities, and we want users to be able to select which one they want to see. There is Vlad's upstream dedup multiplicity, then Duncan's, then mine for the minadcl downsampling. Each is potentially useful for different reasons.

One key thing to keep in mind though is that we won't have 3 multiplicity breakdowns, but instead only 2 if we are doing the seed pruning, as there's no meaningful way to aggregate the multiplicities in that case. So in the UI logic, should make sure that for seed-pruned trees, we only show two selection options for aggregation level.

**Comment by eharkins** [comment]
So do we need to edit our data script to get some aggregation statistics other than multiplicity and cluster_multiplicity to make this happen?

**Comment by metasoarous** [comment]
There may be something like an upstream_multiplicity attribute. If not there could be, but it would have to be introduced earlier on in the data flow, in `bin/process_partis.py`, since this is where we aggregate the Vald's multiplicity metadata together with the partis multiplicity. Frankly though, I think its enough for now to just have the multiplicity and cluster multiplicity. The multiplicity attr accounts for both Vlad's and Duncan's deduplication, and that combined value is enough for now I think, since it corresponds to identity within the region of interest for us.

**Comment by eharkins** [comment]
Fair enough; should I mark this as v1-bonus or low-priority or just put it back in to-do list for now?

**Comment by metasoarous** [comment]
We can mark this as closed for now if you like, since the core issue as outlines has been resolved. We can add a separate issue for adding `upstream_multiplicity`, but I'd tag low-priority and put in the icebox, unless Laura has a specific interest in it.

**Comment by lauradoepker** [comment]
Sounds good.  I read this thread and the summary seems to be that we'll have two multiplicity values: one for Vlad + Duncan (sequence duplicates), the other for CFT (minADCL).  And these two multiplicities will be able to be viewed in Olmsted.  Right?

**Comment by lauradoepker** [comment]
Yes, that's okay because Vlad's dedup deals with same identity + same length sequences.  Duncan's dedup deals with same identity sequences (clipped to same length) and rids the list of seqs that fail health metrics, I believe (out-of-frame, contain STOPs).  👍

**Comment by eharkins** [comment]
Closing and adding icebox issue per @metasoarous suggestion

**Comment by eharkins** [comment]
Closing and adding icebox issue per @metasoarous suggestion
