### ISSUE TITLE
Ability to download newick tree

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#51]
We need the ability to download newick trees of the data, with internal nodes labeled matching the sequence downloads (see #20, #50).

**Comment by metasoarous** [comment]
Just making sure the labels match up and can be used in a join.

**Comment by lauradoepker** [comment]
What's your question?  @metasoarous   Whole-tree fasta download would include duplicate internal node sequences?

**Comment by eharkins** [comment]
@lauradoepker  The whole tree fasta download does exclude duplicate internal node sequences (this is already implemented), but for downloading the newick string of the tree (not yet implemented) I was asking if we have that same requirement or if we just want the full newick string. The newick is agnostic of sequences anyway right? That is unless the answer to this question is that we want to remove nodes we know have the same sequence from the newick.

**Comment by lauradoepker** [comment]
Oh.  Does Newick include node sequences?  Or just node positions (i.e. topology of tree)?  I don't care - I think the Newick should probably be all-inclusive so that folks can download the exactly tree.  Depending on how they render the tree, would branches no longer be collapsed on the x-axis, @metasoarous ?

**Comment by lauradoepker** [comment]
Don't worry about the x-axis comment.  I meant to ask if all the same-sequence (duplicate node) bifurcation branches won't be extending out to the right.  The reason being that branch length means _mutation_ to me, not bifurcation, which is how dnaml usually works.

**Comment by metasoarous** [comment]
@lauradoepker Regarding bifurcation, and how far things extend out to the right along the x-axis: They never _did_ extend out along the x-axis as far as the newick data was concerned. The extension along the x-axis which plagued us early on was just an artifact of how the data was being rendered.

Anyway, sounds like leaving the tree as its been is fine for now.

**Comment by eharkins** [comment]
Clarification: Do we want to just download the newick tree for a selected family (ie have a button right next to the fasta download for a selected family that downloads a one line file containing the newick string for that family)?

**Comment by lauradoepker** [comment]
^Yes @eharkins
