### ISSUE TITLE
Update clonal families scatterplot & table data to have only one entry per family

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#6]
Currently in our data we have duplicate clusters because the seed clusters each have two different trees. One is for the seed lineage pruning strategy, the other is for the minadcl pruning strategy.
Maybe we should have a `trees` or `reconstructions` column in the table so that you can specifically focus on one type of reconstruction over another.
Alternatively, we can have this option just for the selected family's tree: once you've selected a family, then you can choose the type of reconstruction you want for the tree

**Comment by metasoarous** [comment]
@eharkins Take a look at ^ when you get a chance.

**Comment by eharkins** [comment]
Will do!
