### ISSUE TITLE
Fix tree axes/scale

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#60]
We really want this all to match the evolutionary units of the newick trees.

![image](https://user-images.githubusercontent.com/88556/46124661-46396d00-c1da-11e8-887f-41dc3641896c.png)

This may be ultimately tricky because of how we're drawing the svg paths, and there's a bunch of other potentially complicating factors going in on this one as evidenced by #14, #28, #43, #59. I can't help but feeling in looking through all these issues that there isn't some underlying assumption of the work from which olmsted's tree code was inspired which needs to be revised. Could it be something to do with assumptions about how the overall width/height of the viz gets set? Could being more explicit about this improve things?

**Comment by eharkins** [comment]
Just adjusting the scale to match the units of the topological distance from root and span the width of this container seems straightforward to me, I just didn't realize it was a priority so had not spent time on it. In general though I agree that a lot of these issues surrounding the tree size, scale, resizing, etc are interdependent and may benefit from either some bigger picture re-design and/or some simple changes to the code that deals with setting up the viz sizing.
