### ISSUE TITLE
Add ability to zoom on tree

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#64]
Note that this should come after #59 and #63; Idea is that the 90% case of making the tree bigger will probably best be handled by making the width split between the tree and the alignment controllable, such that you can always see the full tree. However, for cases where someone really needs to dig into some detail or cut out noise, this will be a useful feature to have in addition.

Note that the input signal here, `branchZoom` or whatever, should be an input to the `branchScale`, as should the overall `width` of this part of the viz. Not the other way around (as it is now), where `branchScale` is primary and informs `width` and has a complicated relationship with `zoom` (see #28)

For a vega example of zoom:

https://vega.github.io/vega/examples/zoomable-scatter-plot/

And here is an example @eharkins came up with for doing the same just for the x-axis, which is what we want:

[Really long url truncated](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwAVgAMuxREgpG1fFoDM+w1ELo1axjOpbQEI3m6Et7gIwGlIwAbZAAzPB8wUQD3KHZuAm5ULQAmGPdIACdTcxwwfyUAXxtIdFZPWEYAL2QtSBlZWsUlSHhZUNNXQKh0AA9GWC7YozUk9CctUPQg2GQbWMg8RngAawBlatqcC3mMpdWAYW4g7ky6gGIADmuFbuD0dmQggDFZCJxIAFlZdDb5MCOrGyyEyYAAcshlJBuoUis0jJVqDJpoMcABtbpuYb1dCoLZQDCZJhyXZGCjTVj4tIw3ZYhbIvF1RDcKhnUlQWRaDHDdzASDIKgyPCoqAAKiwqG4rFmLJBCigyBkbTU+OMsrOxTuvP5guFdXFkulyClEX+CqV3BVdRC6CokE1PIgfIFir1HwNUtmo2UJPNytVsxC8AiDsdzt1IsgHqNrG8Zr9ltVmSeyHQs3tWoAujTMVAGarepl0M4mlBY2p0HhVWiDGBVBpEJnIGBQ0687jVQBPIsl+WQcuV6smMx4f66Jst+G8rU4xkfb2+yDkoKUrQyVhBILsyCc9Fap0612RzysJCKtR9gdVurrzf29kHl1CyOGr3cH3-E9IWB4dCZU1loQFbXh8vSdgAFAAlBmPLZrErZgHSGT5nUvTwECfbLquOC3luM67mA3JhvuGRPm6BKesgC6flK36-v+NGnigMgXg+GRXgGQTLMg4G9KMqDQSRsKwTmsRIUYKHzk8v6YRS+I1mOmbbgRRE8uJ2JkSKqmOk6JE8pA0hAvAqqqCx759ngnaEKqr5oLKfZtDIsCsHOYB4JklJsfpjx4MoyCKlyfKWdZdS2Qu96IQZUqZMZdSmd6FlWTZlGxvacE6e4CE6epOmLEldRfogkp2v8rSyM5rnuZ5enYh0QRVmcHxkXQhXILAdAhM4LBgAAvH1+TQhlmU1UpNX9kBg51AuYAAPyEQuNaZgAtL0UH-BBkFLQtviZpmYDogY46DY6wnDOlECapiM6ST0SrMmyUBYfJtbjspch7tlY2aXFKBPLcQ3jcB1ZOKyeDgQA5L0CDTMg4P-KtkGQf8IMgmD4OdtDIRw2AG2QU2QlsTlpERq4eUhR8hU-n+AGQHVDV1M1rXtZ11AsH1PUpPeY0cXUaK8fxi1gAA1GAfFJGiO2QWApBgCk61QfjOmnbE52Tld+k3ZAVTcEkskrvivhvVyJFE0Y30fMov1BAAhP9GW06csU4FVczcxNIG2O+4G+HQ+iG2AzUqvV6AAJpgKKYCEF7vgAGz-IH0noN8KqI8dPJZdOAPm5FiLIkEU0DHgnMZwsoSO-iLteYBQMFz+vjS2Ajg-pzQlZqJmfYprTd4L4evYWA6QLCpJtfSTOBBflFO0YgVP-n2dNyk1uotdPbUdYqrOIOzxdV4Dk0fIQThIAAIoXxbGeBZGCUrhOj0epO59MtdF1zAM8-Ohct0rbfwbS10ds-TmpUnpaEHhkFSRNDzPlJsFVUhViqljKk5FyFcPJzCgAvRqCpl5M3Xl1LefUd4kT3h7SAh87qnypkqHiV806ZVVpdMS-9XKQDFskUq78oCwC4hfXoyBeh4Ggv8fC71CIjyzmPHOpg85TUTq-e2nDIBojQkCQWItYB2BkLxdCmQpYRyDr+QWMt6wsHhjoiWe11GaO0UCPRjdE5GLrOoFgisTq3wkffceBlpFPw+NrXWJd2Lu2rOfe6aiwD83FuOMAS0wChNOItOx-jUD-HiZkcJkTUAWJiXEu6CTxxJJ1qgVx6cf6ZT-hrABHxKg1DtgsRR8Agi4kIOBNIDcNHFkyUjfI-x-D6GvsNCAo0WjAUwB9Du9IqmeycHqbcQJ87zkrCIBomQMBBCWikNQkhpAkhnO5YssAy6rONtlKAsCGYCNdPPRgTwLwfFYH2R+CyoB8IEc2QJwAzmTwVJcoU1zbl1AoI8nxzzICdn4REFsZSLpKGGQieAMMtLq07lM1hmNEE1EyNwSYKJXb6X4uMURfInmoX4vIhYPZqD4mJSC1ClLajKzVkwypLCMYIpCH2TF2KcBTBmHi7EBKJjoiWobHa256UP1pR8bsxYqUwUGWAOFPQ+FIuZdidFqENXKWBH8j48REjJHbrpfSGrpVavwjq94UAQjhDoadJVkBCQrFVRMvY3yDKdlQPEfO25QhYuSF40ZdQo4zMGBnVoXFvDOzQduRU-ohiOn5EKReiExp1SCAAeTsPAZgnZSYgJwLoOgMdAlGHTfmuSdQfz+SCOwfW8r05sRIdSsavQH7soLFqjBNygh3LLOSxNeavGmqgGymG-ze2AoHSazYkqkS+K4bOxlv9iHMlZJET5tNGB3i8QW7tyZ2DZFWPaJliabR2jyIhbtO7Ip7oMlWJ4dbVyFFPSalMwYfCbpqdS7x87QXfr7KgDcVrtAvsCVkFMaZqWLtqcOqVMGGVQtKfBWFIBYRAA)

**Comment by metasoarous** [comment]
The latest commit (91faf41) seems to have resolved most of the quirks we talked about when we last met. In particular:

* Setting a maximum zoom seems to be doing a good job of making it easy to get back to square one.
* Disabling scroll when hovered over the alignment is looking good as well.

One little quibble is that the max zoom ends up cutting off labels of the most mutated sequences. Can we add a little padding for these?

![image](https://user-images.githubusercontent.com/88556/48115673-8992ec80-e218-11e8-80f7-04da71e27747.png)

**Comment by eharkins** [comment]
I definitely can add padding for the labels. @metasoarous any thoughts on the dragging / panning? One thing that bothers me still is that if you drag past the edge of the tree and then zoom, it snaps things back so that the edges of the tree are at the edge of the viz again. This has to do with how I limit the zoom to happen within the bounds of the tree, but I haven't figured out how to limit the click to drag to allow you to drag around but stop when you hit the edge. My hope is that I can make that behavior happen

**Comment by eharkins** [comment]
Also the naive becomes no longer visible as the alignment gets zoomed in, which isn't ideal.

**Comment by metasoarous** [comment]
One last thought is that it might be nice to make it so that zoom only works if you're holding Shift or some such, so that folks don't accidentally zoom when they're trying to scroll. Thoughts on this?

**Comment by eharkins** [comment]
Have a working solution for the panning / dragging. Thanks for opening up #100 (100 issues yeehaw). I think the shift thing could be helpful in preventing unwanted zooming, though I feel like if we clearly mark the boundaries of the tree area and change the cursor or make it obvious that that area is zoomable, it might not be necessary.
