### ISSUE TITLE
What do we want to call the x-axis on the tree viz?

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#66]
Some options:

* Distance from naive
* Evolutionary time
* omit entirely

CC @matsen @lauradoepker ?

**Comment by lauradoepker** [comment]
What metric is being measured?  Is it %mutation?  Name it whatever the measurement is.  Distance from naive (hamming distance?).

**Comment by metasoarous** [comment]
I think what we want here is: Evolutionary distance from naive

In our case (dnaml), this is certainly not % mutation or Hamming distance. If we were using parsimony (dnapars), it might be fair to think of it that way. But inherent in the ml of dnaml is the fact that we are looking at a maximum likelihood estimation of a probabilistic phylogenetic model. And in that model, if different mutations have different probabilities, then we'd expect the tree to reflect those probabilities in it's branch lengths. More concretely, if we see an uncommon mutation separating some cluster of sequences from the rest, we would most likely estimate the split to be more evolutionarily distant/long-ago than if it were a very common mutation.

Ideally, this would all be configurable somehow so that different tree types can pass through different information about what their axes mean (there are also time models, of course). This could potentially be plugged in at the metadata level in CFT, so that as new build options are available. The way the data is organized at the moment, there's already some metadata about tree method, etc., so at the very least for now we can use that to fork to decide in the olmsted code what we display if we start adding methods. Additionally, with vega-lite export (see #52), you'd easily be able to export the plot to an editor where you could customize the labels. In short, there are options for the future.

For now, I think "Evolutionary distance from naive" nicely clarifies our current setup, while also (hopefully?) coming off more intuitively and more generally than "Evolutionary time" (since one can think about evolutionary time as a kind of evolutionary distance, but not necessarily the other way around).

Thoughts?
