### ISSUE TITLE
Add style to css class 'vega-bindings' and/or 'vega-bind'

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#67]
This will allow us to style vega dropdowns and sliders if we so choose.

**Comment by metasoarous** [comment]
@eharkins Can you link to some docs on this please?

**Comment by eharkins** [comment]
No, I haven't seen any docs on it in all my parsing through vega docs, but I noticed today that they are given these class names and thought this might be a way to style them if there is no info on how to do so in the docs.

**Comment by metasoarous** [comment]
Word; Should be easy enough to throw some jquery css-selector hooks in there.

**Comment by eharkins** [comment]
I was more just thinking of having some css defined for those classes in global.css

**Comment by metasoarous** [comment]
Oh; Sure. Or that.

**Comment by eharkins** [comment]
Unless we wanted to change the style dynamically, but I don't see any reason to (yet).

**Comment by metasoarous** [comment]
Done
