### ISSUE TITLE
Add sane default selected reconstruction procedure

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#70]
#6 is now closed, as the core problem of that issue has been resolved. But which tree/reconstruction shows up is still random.

@lauradoepker What would your default preference be here for minadcl vs seed lineage selection when we have the option of showing either?

**Comment by lauradoepker** [comment]
Seeded because seed-lineage is only available for trees with seeds (and that's what we'd be looking for) and it'll default to minadcl for non-seed-containing trees.
