### ISSUE TITLE
Selecting datasets should only show data from selected dataset

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#77]
On splash page, choosing a dataset doesn't mean anything as far as what is shown as it stands, this of course needs to change.

**Comment by eharkins** [comment]
The easiest way to make this work right now is to filter all the clonal families (since we must fetch them all at once as they are in the same array in the output file from our data script) based on the dataset.id matching the selected dataset in redux store. A way to simplify that would be to have our data script write them out to separate files or at least as separate arrays in a single file and just fetch the one we need. @metasoarous what are your thoughts on how we should do this for v1?

**Comment by metasoarous** [comment]
Let's just do the simple thing for now.
