### ISSUE TITLE
Highlight seeds in tree

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#78]
Seed sequences should always be highlighted somehow in the tree.

**Comment by eharkins** [comment]
@lauradoepker Should the seed be blue?
![screen shot 2018-10-16 at 1 38 50 pm](https://user-images.githubusercontent.com/12140437/47045915-d834f580-d148-11e8-8c55-c68ccf9d68ce.png)
This helps you pick it out of the tree but not necessarily know what it means; we could also just tack on `(seed)` to the end of the id as a reminder (thinking more about this being used by a broader group of users - but also I guess the seed may be specific to our own pipeline, coming from the seed-lineage reconstruction / partis seed). Any thoughts on this @metasoarous?

**Comment by lauradoepker** [comment]
Yes, blue works, I like color rather than (seed) but either or both are fine.

**Comment by eharkins** [comment]
@metasoarous Our output clonal family objects have the following property: 
```
"seed": {
            "ident": "02cf2182-f9c9-3f79-be74-b5e3bfe7bcce", 
            "id": "QB850.424-Vh"
        }
```
I already highlight the seed in the tree by matching its id with this id string. Is there a way to associate this ident with any of the entities we are using for sequences such as 
`cft.reconstruction:cluster_aa`, `cft.reconstruction:asr_seqs`? (in case there were duplicate sequence names). That is, do you happen to know if cft nests the seed ident in any of the reconstruction entities?

**Comment by metasoarous** [comment]
There shouldn't be duplicate sequence names, and unfortunately there's no linking directly to the seed entity (though it would be great if this was the case). So the solution you have for now is fine.

I think as long as folks can hover on the node and see that it has `is_seed: true`, that's probably fine as far as annotation. If a user has seeds, there's a good chance they are familiar with their seed ids, so this may not need too much attention.

I'm not sure I like blue (or color in general) so much as I like bold.

**Comment by eharkins** [comment]
> I think as long as folks can hover on the node and see that it has `is_seed: true`, that's probably fine as far as annotation. If a user has seeds, there's a good chance they are familiar with their seed ids, so this may not need too much attention.

`is_seed` is not currently a field we have on the sequences and my solution didn't add it but I think we could still show this in the hover info for the seed.
> I'm not sure I like blue (or color in general) so much as I like bold.

I agree with something other than color when possible. Right now we are using bold for the sequence selected from the tree to show in the lineage view below. Some other options are italic or font type or size, or adding on `seed` to the end (or changing the label text in some other way). See https://vega.github.io/vega/docs/marks/text/ for options for the text mark

**Comment by metasoarous** [comment]
How about make unselected labels grey, selected labels black, and seeds bold?

**Comment by eharkins** [comment]
Works for me!

**Comment by eharkins** [comment]
![screen shot 2018-10-25 at 2 20 49 pm](https://user-images.githubusercontent.com/12140437/47531026-35bff500-d861-11e8-8601-0b9466f92fc3.png)
@metasoarous Does the seed jump out at you enough here?

**Comment by metasoarous** [comment]
Hmm... I'm not quite satisfied with that either. Seed vs selected distinction doesn't really pop out at you here. I do like the default grey. I wonder though if seed shouldn't also be a bit darker (if not all the way black), and maybe it's the selected nodes that should be distinguished by color? Maybe dark blue? Could also see us using font size to help distinguish things here.

**Comment by eharkins** [comment]
So either:

A: Bold+maximize the seed and make the selected darker:
![screen shot 2018-10-26 at 10 36 42 am](https://user-images.githubusercontent.com/12140437/47583124-517fd580-d90b-11e8-93a0-3c2bebe93a93.png)

or 
B: The seed remains the darkest and we bold/maximize the selected:
![screen shot 2018-10-26 at 10 35 43 am](https://user-images.githubusercontent.com/12140437/47583110-49c03100-d90b-11e8-9dbf-a0f5a6fb02d8.png)
I prefer A. Let me know if you prefer one or the other @metasoarous @lauradoepker

**Comment by eharkins** [comment]
@lauradoepker Chris and I think that A (see above) works nicely, here is the updated version that we settled on. (changes are that things default to being grey unless clicked on, and that the grey value isn't so invisible):
![Screen Shot 2018-10-26 at 2.58.36 PM.png](https://images.zenhubusercontent.com/5b523735b69de9433c05431a/b5a727cf-ac50-48b0-83c5-3a7ee090e85a)

**Comment by metasoarous** [comment]
@lauradoepker I thought we decided this didn't make sense in the lineage views. Am I wrong about that?

**Comment by lauradoepker** [comment]
Oh totally - I didn't realize this was a lineage view.  My b.

**Comment by metasoarous** [comment]
When we talked about this before I thought we also decided we didn't really need to have multiple selection to show sequences, since they are already being shown in the main sequence alignment. I can see there's some potential value in being able to put a set of sequences right next to each other so it's easier to see what's different between them, but this is a really a separate issue, and we should move discussion over to a new issue to avoid issue-creep if this is the direction we want to head in.

**Comment by eharkins** [comment]
Should I close this? It seems like the main issue here has been resolved. @lauradoepker I can open another issue for selecting multiple based on your thoughts re: Chris' comments. Then we can talk about what behavior we want to have for selecting multiple sequences in that separate issue if we want.
