### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#92]
@eharkins and I have been talking about making some data available so that folks can test out the application more easily. We could just use some simulated data for this, but it would be really great if we could use some of real life, rich data, so that folks can compare subjects/timepoints etc.

@lauradoepker - What of your data would you be comfortable with us using in this fashion? I'm assuming the data for these projects will be open once publications are out, but I wouldn't want to use any data that you were keeping a lid on.

**Comment by psathyrella** [comment]
There's also a bunch of non-laura data from studies that most users will probably be familiar with, e.g. jason-influenza has three subjects and a ton of time points, or jason-mg has a bunch of subjects in different categories of myasthenia gravis.

**Comment by metasoarous** [comment]
Great suggestion! Those builds are a bit older, and don't have `info.yaml` files yet. Do you think the data would process fine if we generated some yaml files in place? Or is it worth also updating the partis build?

**Comment by psathyrella** [comment]
eh, we probably want to rerun partis, it's a trivial amount of work, and the existing stuff is ancient, and I think was for the germline inference paper so probably not actually applicable for cft. What should I run? If we want seeds we'd have to either make up some seeds, or use my random seed seq option. Or just do unseeded?

**Comment by eharkins** [comment]
We now have test data pushed to the repo.

Left to do:
- [ ] add notes to readme re how to use said data
- [ ] remove test datasets with null or incomplete data

**Comment by metasoarous** [comment]
I think we're good here as far as documentation and cleanup. Will have to make sure this data stays up to date as far as build goes, however.
