### ISSUE TITLE
Stoat deployment DB solution

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#93]
We need to have a deployment up on stoat for Laura (and others) to access. The sooner this goes up, the better because we can get feedback before we "release" v1 to make sure it is in working order. We can use tmux in order to keep it running when we disconnect from stoat. The only thing stopping deployment from being practically feasible right now is that loading the JSON data files over the network takes too long because of their size. 

Here is what Chris and I talked about as a spectrum of options from minimum necessity to ideal (@metasoarous let me know if I've left anything out here, please, especially on the "mvp/ easy to reach working solution" end of the spectrum):

**MVP:** Something similar to what cftweb has in place, a direct tripl-querying instance in the server code to fetch clonal family records, reconstructions, and associated data as needed. Did we discuss an even less sophisticated model @metasoarous, where we still are getting data from the local file system, but just in a more efficient way? 

**Intermediate:** Use postgres or some other such SQL db that allows storing blobs which we can use to store a clonal family record or similar high-level nested data structure and query for these upon request. Requires the work of setting up the DB and some code to read and write these JSON blob entities

**Ideal:** Use datomic to store tripl data as facts in a database that allows recursive definition of entities, fits well with our data. Requires more work to set up this DB, write these facts initially from tripl

**Some end-use requirements:**
We perhaps don't mind if things are slow in starting the server/ initially loading olmsted (to a reasonable degree), so long as once one has loaded the page, things move quickly and we are not waiting for data requests.
If we can preserve automated selection of data and quick loading of reconstructions, table results upon brush selection and other things of that nature, that would be ideal.

Sorry for some vagueness here, Chris and I have yet to resolve this conversation.

**Comment by eharkins** [comment]
Working version of Olmsted is now deployed @ http://stoat:3999/ from stoat:/home/matsengrp/working/eharkins/olmsted. The plan is to pull to there when we'd like to update the "live" version of Olmsted meant for use and restart the server if necessary. Regarding loading clonal families JSON files, we are now separating the files by dataset and requesting them on a by-dataset basis, as well as zipping them for faster transfer over the network. This serves our performance needs for now, but this issue will become relevant again as things scale.

**Comment by metasoarous** [comment]
This looks good to me for now. We can revisit when the pain hits again and open up a second issue referring to and copying content from this one as necessary.
