### ISSUE TITLE
Add a loading status gif for large datasets

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#98]
It would mitigate some of the concerns around UX waiting for large data files to download if there was a rotating wheel or whathaveyou to let folks know the data is on its way.

**Comment by eharkins** [comment]
We could put the gif in place of the explore button so that the explore button appears when things are ready for exploration.

**Comment by metasoarous** [comment]
That won't help someone who follows an `/app?selectedDatasets=...` link though. Also, I think it's bad UX to make someone wait to perform an action, versus letting them act when they're ready and wait to see the results.

I'd vote for showing the spinner and "data loading" message on the ` /app` page, and maybe hiding everything else until the data gets in.

**Comment by eharkins** [comment]
Makes sense!

**Comment by metasoarous** [comment]
Looks good to me!
