### ISSUE TITLE
Better dataset loading interface

### ISSUE THREAD

**Issue by metasoarous** [matsengrp/olmsted#99]
Long run, would be great to arrange things so that when you click on a row of the datasets table on the first page, a download status showed up indicating whether the data is cached, loading, or loaded. This sort of requires breaking up requests per dataset though, and so is probably something we'll be saving for later.

**Comment by eharkins** [comment]
Update @metasoarous we are now showing loading status and breaking things up by dataset. Should we close this?

**Comment by metasoarous** [comment]
Looks good to me!
